### ISSUE TITLE
Homebrew

### ISSUE THREAD

**Issue by luckman212** [acheronfail/repgrep#97]
It's funny, for years I've been using my own cobbled-together shell script that used `rg` under the hood, piping to sed to do the replacements. I named it `rgr`. Now I'll probably be ditching that and switching to this awesome looking project!

Just wondering if you're planning to have it added to Homebrew as well? Would be a nice addition.

**Comment by acheronfail** [comment]
I've not had any plans on doing that. It is on [macports](https://ports.macports.org/port/repgrep/) which is a nice way to install things on macOS (without the controversy of `brew`). I myself don't use macOS, but if someone wants to maintain a brew one that's fine with me.

I'll close this issue though, since if it's going to be maintained there it's not going to be done by me (the macports one isn't maintained by me either).
